language: python

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get.
addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

os:
    - linux


python:

    - 3.5
    - 3.4
    - 3.3
    - 2.7

env:
    global:
        # SET DEFAULTS TO AVOID REPEATING IN MOST CASES
        - SETUPTOOLS_VERSION=stable
        - NUMPY_VERSION=1.9
        - ASTROPY_VERSION=stable
        - CONDA_INSTALL='conda install -c astropy-ci-extras --yes'
        - PIP_INSTALL='pip install'
        - INSTALL_OPTIONAL=true
        - SETUP_CMD='test'

   matrix:
        
        # Make sure that egg_info works without dependencies
        - SETUP_CMD='egg_info'

        # Try all python versions with the latest numpy
        - SETUP_CMD='test'


matrix:
    include:

        # Do a coverage test in Python 2. This requires the latest
        # developments version of Astropy, which fixes some issues
        # with coverage testing in affiliated packages
        - python: 2.7
          env: ASTROPY_VERSION=development SETUP_CMD='test --coverage'


        #CHECK SPHINX DOC WARNINGS
        - python: 2.7
          env: ASTROPY_VERSION=development SETUP_CMD='build_sphinx -w'
        - python: 3.4
          env: ASTROPY_VERSION=development SETUP_CMD='build_sphinx -w'

        # Python 3.3 doesn't have numpy 1.10 in conda, revoke this commit
        # once it's available int he astropy-ci-extras channel
        - python: 3.3
          env: SETUP_CMD='egg_info'
        - python: 3.3
          env: SETUP_CMD='test' NUMPY_VERSION=1.9

        #CHECK NUMPY
        - python: 2.7
          env: NUMPY_VERSION=1.9 SETUP_CMD='test'
        - python: 2.7
          env: NUMPY_VERSION=1.8 SETUP_CMD='test'
        - python: 2.7
          env: NUMPY_VERSION=1.7 SETUP_CMD='test'
        - python: 2.7
          env: NUMPY_VERSION=1.6 SETUP_CMD='test'

        #CHECK WITHOUT OPTIONAL DEPENDENCIES
        - python: 2.7
          env: SETUP_CMD='test' CONDA_DEPENDENCIES='Cython'
        - python: 3.5
          env: SETUP_CMD='test' CONDA_DEPENDENCIES='Cython'




install:

    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh


    # Make sure that the interactive matplotlib backends work
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start


    # ASTROPY
    - $PIP_INSTALL git+http://github.com/astropy/astropy.git#egg=astropy
    - $CONDA_INSTALL -n test numpy=$NUMPY_VERSION astropy



script:
   - python setup.py $SETUP_CMD

