language: python

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get.
addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

os:
    - linux


python:

    - 2.7
    - 3.3
    - 3.4
    - 3.5

env:
    global:
        # SET DEFAULTS TO AVOID REPEATING IN MOST CASES
        - SETUPTOOLS_VERSION=stable
        - NUMPY_VERSION=1.9
        - ASTROPY_VERSION=stable
        - CONDA_INSTALL='conda install -c astropy-ci-extras --yes'
        - PIP_INSTALL='pip install'
        - INSTALL_OPTIONAL=true
        - SETUP_CMD='test'


matrix:
    include:

        # Do a coverage test in Python 2. This requires the latest
        # development version of Astropy, which fixes some issues with
        # coverage testing in affiliated packages.
        - python: 2.7
          env: ASTROPY_VERSION=development SETUP_CMD='test --coverage'

        # Do a coverage test in Python 3. This requires the latest
        # development version of Astropy, which fixes some issues with
        # coverage testing in affiliated packages.
        - python: 3.5
          env: ASTROPY_VERSION=development SETUP_CMD='test --coverage'

        #CHECK SPHINX DOC WARNINGS
        - python: 2.7
          env: SETUP_CMD='build_sphinx -w'
        - python: 3.5
          env: SETUP_CMD='build_sphinx -w'

        #CHECK ASTROPY
        - python: 2.7
          env: ASTROPY_VERSION=development SETUP_CMD='build_sphinx -w'
        - python: 3.5
          env: ASTROPY_VERSION=development SETUP_CMD='build_sphinx -w's

        #CHECK NUMPY
        - python: 2.7
        - python: 3.3
        - python: 3.4
        - python: 3.5
          env: NUMPY_VERSION=1.8
        - python: 2.7
          env: NUMPY_VERSION=1.7
        - python: 2.7
          env: NUMPY_VERSION=1.6

        #CHECK WITHOUT OPTIONAL DEPENDENCIES
        - python: 2.7
          env: INSTALL_OPTIONAL=false
        - python: 3.4
          env: INSTALL_OPTIONAL=false
        - python: 3.5
          env: INSTALL_OPTIONAL=false         


before_install:

    # USE UTF8 ENCODING. SHOULD BE DEFAULT, BUT THIS IS INSURANCE AGAINST
    # FUTURE CHANGES
    - export PYTHONIOENCODING=UTF8

    # http://conda.pydata.org/docs/travis.html#the-travis-yml-file
    - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a

    #CHECK INTERACTIVE MATPLOTLIB BACKENDS
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start



install:
    - conda create -c astropy-ci-extras --yes -n test python=$TRAVIS_PYTHON_VERSION
    - source activate test

    # CORE DEPENDENCIES
    - $CONDA_INSTALL -n test  numpy=$NUMPY_VERSION pytest pip Cython jinja2
    - $PIP_INSTALL pytest-xdist
    - $PIP_INSTALL astropy_helpers

    # ASTROPY
    - $PIP_INSTALL git+http://github.com/astropy/astropy.git#egg=astropy
    - $CONDA_INSTALL -n test numpy=$NUMPY_VERSION astropy


    # OPTIONAL DEPENDENCIES
    # Here you can add any dependencies your package may have. You can use
    # conda for packages available through conda, or pip for any other
    # packages. You should leave the `numpy=$NUMPY_VERSION` in the `conda`
    # install since this ensures Numpy does not get automatically upgraded.
    - $CONDA_INSTALL -n test numpy=$NUMPY_VERSION scipy matplotlib

    # DOCUMENTATION DEPENDENCIES
    # build_sphinx needs sphinx and matplotlib (for plot_directive).
    - if [[ $SETUP_CMD == build_sphinx* ]]; then $CONDA_INSTALL -n test numpy=$NUMPY_VERSION Sphinx matplotlib; fi

before_script: # configure a headless display to test plot generation
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start


script:
    - python setup.py install

after_success:
    - if [[ $SETUP_CMD == 'test --coverage' ]]; then coveralls --rcfile='imexam/tests/coveragerc'; fi

