# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.

language: python

os: 
    - linux


python:

    - 2.7
    - 3.3
    - 3.4

env:
    global:
        # SET DEFAULTS TO AVOID REPEATING IN MOST CASES
        - SETUPTOOLS_VERSION=stable        
        - NUMPY_VERSION=1.9
        - ASTROPY_VERSION=stable
        - CONDA_INSTALL='conda install -c astropy-ci-extras --yes'
        - PIP_INSTALL='pip install'  
        - INSTALL_OPTIONAL=true
        - SETUP_CMD='test'
    

matrix:
    include:
    
        #CHECK SPHINX DOC WARNINGS
        - python: 2.7
          env: SETUP_CMD='build_sphinx -w'
        - python: 3.4
          env: SETUP_CMD='build_sphinx -w'
          
        #CHECK ASTROPY
        - python: 2.7
          env: ASTROPY_VERSION=development SETUP_CMD='build_sphinx -w'
        - python: 3.3
          env: ASTROPY_VERSION=development SETUP_CMD='build_sphinx -w's
        
        #CHECK NUMPY
        - python: 2.7
          env: SETUP_CMD='test'
        - python: 3.3
          env: SETUP_CMD='test'
        - python: 3.4
          env: SETUP_CMD='test'
        - python: 2.7
          env: NUMPY_VERSION=1.8 SETUP_CMD='test'
        - python: 2.7 
          env: NUMPY_VERSION=1.7 SETUP_CMD='test'
        - python: 2.7
          env: NUMPY_VERSION=1.6 SETUP_CMD='test'
        
        #CHECK WITHOUT OPTIONAL DEPENDENCIES
        - python: 2.7
          env: INSTALL_OPTIONAL=false
        - python: 3.4
          env: INSTALL_OPTIONAL=false
            
    
        
before_install:

    # USE UTF8 ENCODING. SHOULD BE DEFAULT, BUT THIS IS INSURANCE AGAINST
    # FUTURE CHANGES
    - export PYTHONIOENCODING=UTF8
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes conda
    
    #UPDATE APT-GET LISTINGS
    - sudo apt-get update
   
    #DOCUMENTAITON DEPENDENCIES
    - if [[ $SETUP+CMD == build_sphinx* ]]; then sudo apt-get install graphviz texlive-latex-extra  python-matplotlib dvipng; fi
    
    #CHECK INTERACTIVE MATPLOTLIB BACKENDS
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    


install:
    - conda create -c astropy-ci-extras --yes -n test python=$TRAVIS_PYTHON_VERSION
    - source activate test
    
    # CORE DEPENDENCIES
    - $CONDA_INSTALL -n test  numpy=$NUMPY_VERSION pytest pip Cython jinja2
    - $PIP_INSTALL pytest-xdist

    # ASTROPY
    - $PIP_INSTALL git+http://github.com/astropy/astropy.git#egg=astropy
    - $CONDA_INSTALL -n test numpy=$NUMPY_VERSION astropy

    # OPTIONAL DEPENDENCIES
    # Here you can add any dependencies your package may have. You can use
    # conda for packages available through conda, or pip for any other
    # packages. You should leave the `numpy=$NUMPY_VERSION` in the `conda`
    # install since this ensures Numpy does not get automatically upgraded.
    - $CONDA_INSTALL -n test numpy=$NUMPY_VERSION scipy matplotlib


    # DOCUMENTATION DEPENDENCIES
    # build_sphinx needs sphinx and matplotlib (for plot_directive).
    - if [[ $SETUP_CMD == build_sphinx* ]]; then $CONDA_INSTALL -n test numpy=$NUMPY_VERSION Sphinx matplotlib; fi


script:
   - python setup.py $SETUP_CMD
